---
name: xnetcdf
channels:
  - conda-forge
  - nodefaults

dependencies:
  # core dependencies
  - numpy >=2
  - python >=3.11  # pinned Zarr, pyfive and umfive
  # all backends
  - dask
  - fsspec
  - netCDF4 !=1.7.4  # github.com/Unidata/netcdf4-python/issues/1464
  - h5py
  - scipy
  - pyfive >=1.1.1
  - umfive >=0.2.2
  - zarr >=3.1.3
  - xarray
  # testing and linting
  - h5netcdf
  - pre-commit  # with ruff and mypy
  - pytest
  - pytest-cov
  - pytest-html
  - pytest-xdist
  # documentation dependencies
  - autodocsumm
  - sphinx
  - furo
